### PR TITLE
Add Appveyor config file

### LINKED ISSUE #19: Fix appveyor.yml
Primary users will be Windows users. Appveyor.yml is not set up properly yet. 

*Preferably test on Python 3.7, but if not available, 3.6 should be sufficient, although plan is to package with a Python 3.7 virtualenv interpreter.

*32 and 64 bit implementations also needed.

### PR DESCRIPTION
**Pull request by mbarakaja**
This pull request add the yml file for AppVeyor. It is setup to test under python3.6 and python3.7 both x64.

Closes #19

### CODE REVIEW

**Comment by mbarakaja** [comment]
Well, AppVeyor are failing to pickup 32-bit version of python3.6 and 3.7. Let me see what happening.

**Comment by mbarakaja** [comment]
Now you need to create an AppVeyor account and add this repository to it. My fork is already working

**Comment by toonarmycaptain** [comment]
Thanks so much :)

**Comment by toonarmycaptain** [comment]
@all-contributors please add @mbarakaja for infra

**Pull request merged**
