### PR TITLE
That's how you can write tests for your create-class functionality :)

### PR DESCRIPTION
**Pull request by Ginkooo**

### CODE REVIEW

**Comment by Ginkooo** [comment]
Tests now can be run with `pytest -s` to prevent stdout/stderr capturing

**Comment by Ginkooo** [comment]
Your CodeFactor stands that I use `input()` function from Python 2, but I'm using Python 3 `input()`, coult you fix it?

**Comment by toonarmycaptain** [comment]
> Your CodeFactor stands that I use input() function from Python 2, but I'm using Python 3 input(), coult you fix it?

I've been trying to figure this out myself. Codefactor has a setting for 2.7 or 3.6, and it's set for 3.6, but it still flags some instances of `input()` - I've just been ignoring them. I think a custom config might be able to address it, but that feels like more effort than it's worth when it's a bug on Codefactor's part.

**Comment by toonarmycaptain** [comment]
I'm going to wait on merging this for a bit, as I did some cleaning/refactoring in [this commit](https://github.com/toonarmycaptain/dionysus/commit/58578a390abd2fcc40adb49c3269f21c49c395ac), alongside [switching over to JSON](https://github.com/toonarmycaptain/dionysus/tree/switch_to_JSON). 

Can you explain why making a class is better? I expect to reuse some of those functions when an Edit class option is implemented, #15

**Comment by toonarmycaptain** [comment]
Actually, I can merge this now if you remove the commit where you [refactor into a class](https://github.com/toonarmycaptain/dionysus/pull/31/commits/a988ac96979da9adff153d6f3f37851c5e02c59b), and we can discuss that idea for a future update?

I really hadn't considered using classes, I'd just meant [rearranging](https://github.com/toonarmycaptain/dionysus/issues/30): 
> Reorganise the functions so that they're easier to find. eg function definitions found after the function they're first called from, reading from the top of the script, in the order they appear in the calling function. 
And what I meant was I'd been trying to follow that pattern:

```
def func_a():
  func_b()
  func_c()

def func_b():
  pass

def func_c():
  func_d()
  func_f()

def func_d():
  func_b()
  func_e()

def func_e():
  pass

def func_f():
  pass
```
...but it had gotten a bit muddled.

**Comment by toonarmycaptain** [comment]
Caught up class_functions.py, main_menu.py to current master, reversing change to classed version of class_functions.py. Fixed tests broken by catchup to master. 

Classed form of class_functions.py can be considered at a later date. 

Issue CodeFactor is finding is use of Python2 `input()` again. This is a false flag, as project is Python3.

Thankyou @Ginkooo for your contribution :)
I'm adding a #TODO to widen the tests to include potentially problematic input. 

In future let's have PRs doing one thing at a time. This makes things easier to manage.

**Comment by toonarmycaptain** [comment]
@all-contributors please add @Ginkooo  for code, tests

**Pull request merged**
